Sprint_3
vvilin98/Sprint_3 pull request #1
Opened 2023-04-28 20:08 UTC by vvilin98

2023-04-29 08:05 UTC, kadirovgm requested changes

2023-04-29 08:05 UTC, kadirovgm commented on tests/test_login_logout.py
> +         driver.find_element(*locators.locator_email_field).send_keys('vvilin98@yandex.ru')
Можно лучше: уже писал выше, что такие тестовые данные лучше выносить отдельно 

Так как при масштабировании проекта тебе придется часто их переиспользовать, к тому же это упрощает поддержку при частых изменениях в коде

2023-04-29 08:05 UTC, kadirovgm commented on tests/test_login_logout.py
> +         assert driver.current_url == urls.url_main_paige
Нужно исправить, наличие URL не означает, что страница прогрузилась, лучше помимо этого также проверить, что какой либо элемент страницы прогрузился и отображается корректно. 
Также здесь ты проверяешь авторизацию, поэтмуо надо проверить, что авторизация успешна, по какому параметру это можно проверить - подумай

2023-04-29 08:05 UTC, kadirovgm commented on tests/test_login_logout.py
> +         assert driver.current_url == urls.url_main_paige
Нужно исправить: здесь также - эта проверка не гарантирует, что человек авторизовался

2023-04-29 08:05 UTC, kadirovgm commented on tests/test_login_logout.py
> +         assert driver.current_url == urls.url_main_paige
Нужно исправить: также проверку дополнить

2023-04-29 08:05 UTC, kadirovgm commented on tests/test_login_logout.py
> +         assert driver.current_url == urls.url_main_paige
Нужно исправить: также проверку дополнить

2023-04-29 08:05 UTC, kadirovgm commented on tests/test_login_logout.py
> +        assert driver.current_url == urls.url_login
Нужно исправить: также проверку дополнить

2023-04-29 08:05 UTC, kadirovgm commented on tests/test_profile_form.py
> +        assert len(h1_tag) > 0 and h1_tag[0].text == 'Соберите бургер'
Отлично! вот здесь хорошо

2023-04-29 08:05 UTC, kadirovgm commented on tests/test_profile_form.py
> +        assert urls.url_profile == driver.current_url
Нужно исправить: также проверку дополнить

2023-04-29 08:05 UTC, kadirovgm commented on tests/test_registration.py
> +        assert driver.current_url == urls.url_login
Нужно исправить: также проверку дополнить

2023-04-29 08:05 UTC, kadirovgm commented on tests/test_registration.py
> +    @pytest.mark.parametrize('email_list', ['test1@yanru','test2yan.ru','te st3@yan.ru', 'test4@ya n.ru', '@yan.ru', 'test6@.ru', 'test7@yan.'])
Можно лучше: тестовые данные лучше вынести в отдельный файл и класс

2023-04-29 08:52 UTC, vvilin98 commented on tests/locators.py
> +class Locators:
[kadirovgm](https://github.com/kadirovgm) Привет, хорошая мысль , я правильно понимаю что это по сути увеличит быстродействие ? или только для "удобства"

2023-04-29 16:47 UTC, vvilin98 commented on conftest.py
> +    driver.find_element(*locators.locator_email_field).send_keys(
+

2023-04-29 16:47 UTC, vvilin98 commented on tests/test_constructor_form.py
> +locators = Locators()
"+"

2023-04-29 16:48 UTC, vvilin98 commented on tests/test_login_logout.py
> +locators = Locators()
"+"

2023-04-29 16:52 UTC, vvilin98 commented on tests/test_login_logout.py
> +         driver.find_element(By.XPATH, ".//button[text()='Войти в аккаунт']").click()
"+"

2023-04-29 16:52 UTC, vvilin98 commented on tests/test_login_logout.py
> +         driver.find_element(*locators.locator_email_field).send_keys('vvilin98@yandex.ru')
"+"

2023-04-29 19:20 UTC, vvilin98 commented on tests/test_constructor_form.py
> +        assert "tab_tab_type_current" in driver.find_element(*locators.locator_sauces_button).get_attribute('class'), "Не работает переход на выбор соусов"
"+"

2023-04-29 19:20 UTC, vvilin98 commented on tests/test_constructor_form.py
> +        assert "tab_tab_type_current" in driver.find_element(*locators.locator_sauces_ban).get_attribute('class'), "Не работает переход на выбор булок"
"+"

2023-04-29 19:20 UTC, vvilin98 commented on tests/test_constructor_form.py
> +        assert "tab_tab_type_current" in driver.find_element(*locators.locator_sauces_filling).get_attribute('class'), "Не работает переход на выбор Начинки"
"+"

2023-04-29 19:43 UTC, vvilin98 commented on tests/test_login_logout.py
> +         assert driver.current_url == urls.url_main_paige
"+"

2023-04-29 19:44 UTC, vvilin98 commented on tests/test_login_logout.py
> +         assert driver.current_url == urls.url_main_paige
"+"

2023-04-29 19:44 UTC, vvilin98 commented on tests/test_login_logout.py
> +         assert driver.current_url == urls.url_main_paige
"+"

2023-04-29 19:44 UTC, vvilin98 commented on tests/test_login_logout.py
> +         assert driver.current_url == urls.url_main_paige
"+"

2023-04-29 19:44 UTC, vvilin98 commented on tests/test_login_logout.py
> +        assert driver.current_url == urls.url_login
"+"

2023-04-29 19:44 UTC, vvilin98 commented on tests/test_profile_form.py
> +        assert urls.url_profile == driver.current_url
"+"

2023-04-29 19:46 UTC, vvilin98 commented on tests/test_registration.py
> +        assert driver.current_url == urls.url_login
"+"

2023-04-29 19:55 UTC, vvilin98 commented on tests/test_registration.py
> +        assert driver.current_url == urls.url_login
"+"

2023-04-29 20:07 UTC, vvilin98 commented on tests/test_profile_form.py
> +        assert urls.url_profile == driver.current_url
"+"

2023-04-30 07:08 UTC, kadirovgm commented on tests/locators.py
> +class Locators:
@vvilin98 нет, это никак не повлияет на на скорость. Но смотри, если мы разделим локаторы на классы по страницам, то мы сможем переиспользовать названия переменных, ну и в целом лаконичность в том, что ты импортишь только нужный пулл переменных с локаторами в нужный тестовый файл.

К слову о переиспользовании: на страницах MainPage и AuthPage могут быть свои NEXT_BUTTON - ы , тогда тебе можно будет легко оба обозвать так, и не придумывать. Прим. MainPage.NEXT_BUTTON и AuthPage.NEXT_BUTTON

2023-04-30 07:17 UTC, kadirovgm approved these changes

2023-04-30 07:17 UTC, kadirovgm commented on tests/data.py
> +    password = f"{random.randint(100, 999)}+{random.randint(100, 999)}"
Отлично!

2023-04-30 12:01 UTC, merged